package com.schedulemaster.app;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package com.mycompany.ui_hsh;

import javax.swing.JPanel;

/**
 *
 * @author hansa
 */
public class app_ui extends javax.swing.JFrame {
    public JPanel current_panel = null;
    /**
     * Creates new form app_ui
     */
    public app_ui() {
        initComponents(); //빌더에서 생성한 초기화 메서드, 읽기 전용
        myinitComponents(); //내가 추가로 생성하는 코드
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        title = new javax.swing.JPanel();
        XButton = new javax.swing.JLabel();
        minButton = new javax.swing.JLabel();
        logInPanel = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        logInBtn = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        GotoMagic = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Timetable = new javax.swing.JButton();
        StatusPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        magicPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        GotoMain = new javax.swing.JButton();
        magicList = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        GotoMain_ML = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setBackground(new java.awt.Color(0, 153, 153));
        title.setPreferredSize(new java.awt.Dimension(1000, 75));

        XButton.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        XButton.setForeground(new java.awt.Color(255, 255, 255));
        XButton.setText("X");
        XButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XButtonMouseClicked(evt);
            }
        });

        minButton.setBackground(new java.awt.Color(255, 255, 255));
        minButton.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        minButton.setForeground(new java.awt.Color(255, 255, 255));
        minButton.setText("--");
        minButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
                titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleLayout.createSequentialGroup()
                                .addContainerGap(935, Short.MAX_VALUE)
                                .addComponent(minButton)
                                .addGap(18, 18, 18)
                                .addComponent(XButton)
                                .addGap(14, 14, 14))
        );
        titleLayout.setVerticalGroup(
                titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(titleLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(XButton)
                                        .addComponent(minButton))
                                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        logInPanel.setBackground(new java.awt.Color(255, 255, 255));
        logInPanel.setPreferredSize(new java.awt.Dimension(1000, 425));

        id.setText("id");
        id.setToolTipText("");

        password.setText("password");
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        jLabel5.setText("Hello World");

        logInBtn.setText("logIn");
        logInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logInPanelLayout = new javax.swing.GroupLayout(logInPanel);
        logInPanel.setLayout(logInPanelLayout);
        logInPanelLayout.setHorizontalGroup(
                logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(logInPanelLayout.createSequentialGroup()
                                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(logInPanelLayout.createSequentialGroup()
                                                .addGap(446, 446, 446)
                                                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5)))
                                        .addGroup(logInPanelLayout.createSequentialGroup()
                                                .addGap(438, 438, 438)
                                                .addComponent(logInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(472, Short.MAX_VALUE))
        );
        logInPanelLayout.setVerticalGroup(
                logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logInPanelLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel5)
                                .addGap(43, 43, 43)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logInBtn)
                                .addContainerGap(222, Short.MAX_VALUE))
        );

        getContentPane().add(logInPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1000, 430));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(1000, 425));

        jLabel1.setText("mainPanel");

        GotoMagic.setText("GoToMagic");
        GotoMagic.setToolTipText("");
        GotoMagic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GotoMagicActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        Timetable.setText("timetable");
        Timetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimetableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(GotoMagic)
                                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 329, Short.MAX_VALUE)
                                                                .addComponent(Timetable)))))
                                .addGap(64, 64, 64))
        );
        mainPanelLayout.setVerticalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addGap(151, 151, 151)
                                                .addComponent(Timetable)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                                .addComponent(GotoMagic)
                                .addContainerGap())
        );

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 420));

        StatusPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("status panel");

        javax.swing.GroupLayout StatusPanelLayout = new javax.swing.GroupLayout(StatusPanel);
        StatusPanel.setLayout(StatusPanelLayout);
        StatusPanelLayout.setHorizontalGroup(
                StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StatusPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addContainerGap(927, Short.MAX_VALUE))
        );
        StatusPanelLayout.setVerticalGroup(
                StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StatusPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addContainerGap(397, Short.MAX_VALUE))
        );

        getContentPane().add(StatusPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1000, 420));

        magicPanel.setBackground(new java.awt.Color(255, 255, 255));
        magicPanel.setPreferredSize(new java.awt.Dimension(1000, 425));

        jLabel2.setText("maigic panel");

        GotoMain.setText("GoToMain");
        GotoMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GotoMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout magicPanelLayout = new javax.swing.GroupLayout(magicPanel);
        magicPanel.setLayout(magicPanelLayout);
        magicPanelLayout.setHorizontalGroup(
                magicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(magicPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(magicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(GotoMain))
                                .addContainerGap(906, Short.MAX_VALUE))
        );
        magicPanelLayout.setVerticalGroup(
                magicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(magicPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GotoMain)
                                .addContainerGap(368, Short.MAX_VALUE))
        );

        getContentPane().add(magicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1000, 420));

        magicList.setBackground(new java.awt.Color(255, 255, 255));
        magicList.setPreferredSize(new java.awt.Dimension(1000, 425));

        jLabel3.setText("magicList");

        GotoMain_ML.setLabel("GoToMain");
        GotoMain_ML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GotoMain_MLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout magicListLayout = new javax.swing.GroupLayout(magicList);
        magicList.setLayout(magicListLayout);
        magicListLayout.setHorizontalGroup(
                magicListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(magicListLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(magicListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(GotoMain_ML))
                                .addContainerGap(906, Short.MAX_VALUE))
        );
        magicListLayout.setVerticalGroup(
                magicListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(magicListLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GotoMain_ML)
                                .addContainerGap(368, Short.MAX_VALUE))
        );

        getContentPane().add(magicList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1000, 420));

        pack();
    }// </editor-fold>
    private void myinitComponents() {
        current_panel = logInPanel;
        magicPanel.setVisible(false);
        mainPanel.setVisible(false);
        magicList.setVisible(false);
        StatusPanel.setVisible(false);
    }

    private void GotoMagicActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        current_panel.setVisible(false);
        magicPanel.setVisible(true);
        current_panel = magicPanel;
    }

    private void GotoMainActionPerformed(java.awt.event.ActionEvent evt) {
        current_panel.setVisible(false);
        mainPanel.setVisible(true);
        current_panel = mainPanel;       // TODO add your handling code here:
    }

    private void GotoMain_MLActionPerformed(java.awt.event.ActionEvent evt) {
        current_panel.setVisible(false);
        mainPanel.setVisible(true);
        current_panel = mainPanel;    // TODO add your handling code here:
    }

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void logInBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        current_panel.setVisible(false);
        mainPanel.setVisible(true);
        current_panel = mainPanel;
    }

    private void TimetableActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        //new testTable().setVisible(true);
    }

    private void minButtonMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        this.setState(app_ui.ICONIFIED);
    }

    private void XButtonMouseClicked(java.awt.event.MouseEvent evt) {
        System.exit(0);       // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //current_panel = mainPanel;
        //current_panel.setVisible(true);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(app_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(app_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(app_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(app_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new app_ui().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton GotoMagic;
    private javax.swing.JButton GotoMain;
    private javax.swing.JButton GotoMain_ML;
    private javax.swing.JPanel StatusPanel;
    private javax.swing.JButton Timetable;
    private javax.swing.JLabel XButton;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logInBtn;
    private javax.swing.JPanel logInPanel;
    private javax.swing.JPanel magicList;
    private javax.swing.JPanel magicPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel minButton;
    private javax.swing.JTextField password;
    private javax.swing.JPanel title;
    // End of variables declaration
}
